version: '3.8'

services:
  kafka-ui-ts:
    container_name: kafka-ui-ts
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka-ts
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      SERVER_SERVLET_CONTEXT_PATH: /kafka-ui-ts
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-ts:9092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect0:8083
    networks:
      - ts-network

  zookeeper-ts:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-ts
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ts-network

  kafka-ts:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-ts
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-ts:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-ts:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka-ts -Dcom.sun.management.jmxremote.rmi.port=9997
    depends_on:
      - zookeeper-ts
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - ts-network

  redis-ts:
    image: 'redis:latest'
    container_name: redis-ts
    command:
      - --requirepass secret
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=secret
    networks:
      - ts-network

  worker-ts:
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - ./config_multi_worker.yaml:/app/config/config.yaml
    environment:
      - BROKERS=kafka-ts:9092
      - REDIS_HOST=redis-ts:6379
      - REDIS_PASS=secret
    depends_on:
      kafka-ts:
        condition: service_healthy
      redis-ts:
        condition: service_started
    networks:
      - ts-network
    deploy:
      replicas: 3

  nginx-ts:
    container_name: nginx-ts
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8088:8088"
    networks:
      - ts-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - worker-ts

networks:
  ts-network:
    driver: bridge
