frequency: 100
httpServer:
  port: 8088
  mode: debug # or release
  contextPath: /api/

storage:
  redisHost: localhost:6379
  redisPass: ${REDIS_PASS}
  redisDb: 0
  schedulerChanel: Scheduler
  taskExecutionChanel: TaskExecution
  schedulerKeyName: scheduled_tasks
