frequency: 100
workerEnable: true #pub-sub only and no worker will execute the tasks
httpServer:
  port: 8088
  mode: debug # or release
  contextPath: /

storage:
  redisHost: localhost:6379
  redisPass: ${REDIS_PASS}
  redisDb: 0
  schedulerChanel: Scheduler
  taskExecutionChanel: TaskExecution
  schedulerKeyName: scheduled_tasks

kafka:
  enabled: true
  brokers: localhost:9092
  group: scheduler
  schedulerTopic: Scheduler
  taskExecutionTopic: TaskExecution
